name: Publish release

on:
  push:
    tags:
      - "**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: Generate Release Body
        run: node .github/scripts/release.mjs > RELEASE_BODY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: "${{ github.workspace }}/RELEASE_BODY.md"
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GH_TOKEN }}
