name: Publish to npm

on: workflow_dispatch

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    permissions:
      contents: "write"
      packages: "write"
      actions: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: |
          git config user.name florent giraud
          git config user.email hello@florent.dev
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm i -g pnpm && pnpm install
      - run: pnpm tca:release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
